-- TABELA PERFIL NÃO PRECISA DE DADOS
INSERT INTO PERFIL(nome) VALUES('CLIENTE');
INSERT INTO PERFIL(nome) VALUES('RESTAURANTE');
INSERT INTO PERFIL(nome) VALUES('ENTREGADOR');

-- TABELA STATUS NÃO PRECISA DE DADOS
INSERT INTO STATUS(NOME) VALUES ('ABERTO');
INSERT INTO STATUS(NOME) VALUES ('PREPARANDO');
INSERT INTO STATUS(NOME) VALUES ('ATRIBUIDO');
INSERT INTO STATUS(NOME) VALUES ('ENTREGUE');

-- TABELA TIPO ENTREGA NÃO PRECISA DE DADOS
INSERT INTO TIPO_ENTREGA(NOME) VALUES ('BUSCAR');
INSERT INTO TIPO_ENTREGA(NOME) VALUES ('ENTREGAR');

-- TABELA USUARIO PODE FAZER MAIS UNS 10
INSERT INTO USUARIO(email, senha,perfil_id) VALUES('GUILHERME@GMAIL.COM', 'FIAP01',1);
INSERT INTO USUARIO(email, senha,perfil_id) VALUES('MARCELLO@GMAIL.COM', 'FIAP01',2);
INSERT INTO USUARIO(email, senha,perfil_id) VALUES('TADAO@GMAIL.COM', 'FIAP01',3);
INSERT INTO USUARIO(email, senha,perfil_id) VALUES('ALAN@GMAIL.COM', 'FIAP01',1);
INSERT INTO USUARIO(email, senha,perfil_id) VALUES('JUBILEU@GMAIL.COM', 'FIAP01',2);

-- TABELA CATEGORIA DO RESTAURANTE, AQUI QUANTO MAIS MELHOR
INSERT INTO CATEGORIA_RESTAURANTE(nome) VALUES ('LANCHE');
INSERT INTO CATEGORIA_RESTAURANTE(nome) VALUES ('ARABE');


-- TABELA CLIENTE,ENTREGADOR, ENTREGADOR FAZ ATÉ CHEGAR 7 DE CADA  (LEMBRA QUE TEM Q ENCAIXAR COM A QUANTIDADE DE USUARIOS)
INSERT INTO CLIENTE(cpf,nome, sobrenome, telefone, idade, usuario_id) VALUES('123123','Fulano','Ciclano', '1234-1234', 30,1);
INSERT INTO CLIENTE(cpf,nome, sobrenome, telefone, idade, usuario_id) VALUES('123123','Alan','Zica', '1234-1234', 50,4);
INSERT INTO RESTAURANTE(cnpj,nome, email, telefone, imagem, usuario_id, categoria_restaurante_id) VALUES('123123','Fulano Restaurante','RESTAURANTE@TOP.COM','1234-1234',null, 2,1);
INSERT INTO RESTAURANTE(cnpj,nome, email, telefone, imagem, usuario_id, categoria_restaurante_id) VALUES('123123','JubileuRestaurante','RESTAURANTE@TOP.COM','1234-1234',null, 5,2);
INSERT INTO ENTREGADOR(cpf,nome, sobrenome, telefone, idade, usuario_id) VALUES('123123','Beltrano','Ciclano', '1234-1234', 40,3);

-- TABELA LOCAL VC COLOCA MAIS ESTADIOS DE SP
INSERT INTO LOCAL(NOME,EMAIL,TELEFONE, ENDERECO) VALUES('Arena-Corinthians','ArenaCorinthians@gmail.com','1234-1234',' Av. Miguel Ignácio Curi, 111');
INSERT INTO LOCAL(NOME,EMAIL,TELEFONE, ENDERECO) VALUES('Arena-Palmeiras','ArenaPalmeiras@gmail.com','1234-1234',' Av. Francisco Matarazzo, 1705');

-- TABELA SETOR VC COLOCA OS NOMES DE SETORES QUE EXISTEM NOS ESTADIOS DE SP
INSERT INTO SETOR(NOME) VALUES ('NORTE');
INSERT INTO SETOR(NOME) VALUES ('SUL');
INSERT INTO SETOR(NOME) VALUES ('LESTE');
INSERT INTO SETOR(NOME) VALUES ('OESTE');

-- TABELA BLOCO VC COLOCA OS NOMES DO BLOCO MAIS O NUMERO DA CADEIRA QUE EXISTEM NOS ESTADIOS DE SP
INSERT INTO BLOCO(NOME, NUMERO) VALUES ('A',10);
INSERT INTO BLOCO(NOME, NUMERO) VALUES ('B',20);
INSERT INTO BLOCO(NOME, NUMERO) VALUES ('C',30);

-- TABELA LOCAL_SETOR É A QUE JUNTA O LOCAL COM O SETOR (TIPO ARENA CORINTHIANS, TEM LESTE, OESTE, NORTE .... SEGUE ISSO
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (1,1);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (1,2);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (1,3);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (1,4);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (2,1);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (2,2);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (2,3);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (2,4);

-- TABELA LOCAL_SETOR_ BLOCO, AQUI JUNTA O LOCAL_SETOR INFORMADO COM OS BLOCOS (TIPO ARENA CORINTHIANS NO LOCAL_SETOR(ARENA COR, LESTE) TEM OS BLOCO A B C D...
INSERT INTO LOCAL_SETOR_BLOCO(LOCAL_SETOR_ID, BLOCO_ID) VALUES (1,1);
INSERT INTO LOCAL_SETOR_BLOCO(LOCAL_SETOR_ID, BLOCO_ID) VALUES (1,2);
INSERT INTO LOCAL_SETOR_BLOCO(LOCAL_SETOR_ID, BLOCO_ID) VALUES (1,3);
INSERT INTO LOCAL_SETOR_BLOCO(LOCAL_SETOR_ID, BLOCO_ID) VALUES (2,1);
INSERT INTO LOCAL_SETOR_BLOCO(LOCAL_SETOR_ID, BLOCO_ID) VALUES (2,2);
INSERT INTO LOCAL_SETOR_BLOCO(LOCAL_SETOR_ID, BLOCO_ID) VALUES (2,3);

-- TABELA PRODUTO, AQUI VAI TER A CATEGORIA DO PRODUTO, OS NOMES, QUANTO MAIS MELHOR
INSERT INTO PRODUTO(CATEGORIA_PRODUTO) VALUES ('HAMBURGUER');
INSERT INTO PRODUTO(CATEGORIA_PRODUTO) VALUES ('REFRIGERANTE');
INSERT INTO PRODUTO(CATEGORIA_PRODUTO) VALUES ('HOT-DOG');

-- TABELA RESTAURANTE_PRODUTO, AQUI VAI TER OS PRODUTOS DO RESTAURANTE OS NOMES, QUANTO MAIS MELHOR
INSERT INTO RESTAURANTE_PRODUTO(HABILITADO_VENDA, PRECO, IMAGEM, NOME_PERSONALIZADO, DETALHES, RESTAURANTE_ID, PRODUTO_ID) VALUES (true, 29.90, null, 'HAMBURGUER CHEDDAR', 'SUCULENTO E BOM, MT QUEIJO, E CARNE GRANDE', 1, 1);
INSERT INTO RESTAURANTE_PRODUTO(HABILITADO_VENDA, PRECO, IMAGEM, NOME_PERSONALIZADO, DETALHES, RESTAURANTE_ID, PRODUTO_ID) VALUES (true, 49.90, null, 'COCA-COLA','BEBIDA GELADA, LATA', 1, 2);

-- TABELA CLIENTE_LOCAL_SETOR_BLOCO É A TABELA QUE VAI ESTAR SALVO A LOCALIZAÇÃO DO CLIENTE NO ESTADIO, AQUI VC CRIA PRA BATER A QUANTIDADE COM A DE CLIENTE
INSERT INTO CLIENTE_LOCAL_SETOR_BLOCO(CLIENTE_ID, LOCAL_SETOR_BLOCO_ID, DATA_PRESENTE) VALUES (1,1,CURRENT_DATE);

-- TABELA ENTREGADOR_LOCAL_SETOR É A TABELA QUE VAI ESTAR SALVO A LOCALIZAÇÃO DO ENTREGADOR NO ESTADIO, AQUI VC CRIA PRA BATER A QUANTIDADE COM A DE ENTREGADOR
INSERT INTO ENTREGADOR_LOCAL_SETOR(ENTREGADOR_ID, LOCAL_SETOR_ID, DATA_PRESENTE) VALUES (1,1, CURRENT_DATE);

-- TABELA RESTAURANTE_LOCAL_SETOR É A TABELA QUE VAI ESTAR SALVO A LOCALIZAÇÃO DO RESTAURANTE NO ESTADIO, AQUI VC CRIA PRA BATER A QUANTIDADE COM A DE RESTAURANTE
INSERT INTO RESTAURANTE_LOCAL_SETOR(RESTAURANTE_ID, LOCAL_SETOR_ID) VALUES (1,1);

-- TABELA DE PEDIDO, AQUI VC COLOCA AS INFORMAÇOES DO PEDIDO COM STATUS DIFERENTES E TIPOS DE ENTREGA DIFERENTE E COM O ID DO ENTREGADOR, NULL EM ALGUNS CASOS TBM, VAI CRIANDO.
INSERT INTO PEDIDO(DATA, HORA, AVALIACAO_PEDIDO, AVALIACAO_ENTREGADOR, CLIENTE_LOCAL_SETOR_BLOCO_ID,RESTAURANTE_LOCAL_SETOR_ID, ENTREGADOR_LOCAL_SETOR_ID, TIPO_ENTREGA_ID, STATUS_ID) VALUES (CURRENT_DATE, CURRENT_TIME,5,5, 1,1,1,2,4);
INSERT INTO PEDIDO(DATA, HORA, AVALIACAO_PEDIDO, AVALIACAO_ENTREGADOR,CLIENTE_LOCAL_SETOR_BLOCO_ID,RESTAURANTE_LOCAL_SETOR_ID, ENTREGADOR_LOCAL_SETOR_ID, TIPO_ENTREGA_ID, STATUS_ID) VALUES (CURRENT_DATE, CURRENT_TIME,5,5, 1,1,NULL,2,1);


-- TABELA DO DOS PRODUTOS DO PEDIDO, AQUI CONTEM OS PRODUTOS NO PEDIDO
INSERT INTO PEDIDO_PRODUTO(QUANTIDADE, OBSERVACAO, RESTAURANTE_PRODUTO_ID, PEDIDO_ID) VALUES (1,NULL,1,1);
INSERT INTO PEDIDO_PRODUTO(QUANTIDADE, OBSERVACAO, RESTAURANTE_PRODUTO_ID, PEDIDO_ID) VALUES (1,NULL,1,1);

INSERT INTO CARRINHO(CLIENTE_LOCAL_SETOR_BLOCO_ID, RESTAURANTE_PRODUTO_ID, QUANTIDADE, OBSERVACAO) VALUES (1,1, 1,NULL);