INSERT INTO PERFIL(nome) VALUES('CLIENTE');
INSERT INTO PERFIL(nome) VALUES('RESTAURANTE');
INSERT INTO PERFIL(nome) VALUES('ENTREGADOR');

INSERT INTO STATUS(NOME) VALUES ('ABERTO');
INSERT INTO STATUS(NOME) VALUES ('PREPARANDO');
INSERT INTO STATUS(NOME) VALUES ('ATRIBUIDO');
INSERT INTO STATUS(NOME) VALUES ('ENTREGUE');

INSERT INTO TIPO_ENTREGA(NOME) VALUES ('BUSCAR');
INSERT INTO TIPO_ENTREGA(NOME) VALUES ('ENTREGAR');

INSERT INTO USUARIO(email, senha,perfil_id) VALUES('GUILHERME@GMAIL.COM', 'FIAP01',1);
INSERT INTO USUARIO(email, senha,perfil_id) VALUES('MARCELLO@GMAIL.COM', 'FIAP01',2);
INSERT INTO USUARIO(email, senha,perfil_id) VALUES('TADAO@GMAIL.COM', 'FIAP01',3);
INSERT INTO USUARIO(email, senha,perfil_id) VALUES('ALAN@GMAIL.COM', 'FIAP01',1);
INSERT INTO USUARIO(email, senha,perfil_id) VALUES('JUBILEU@GMAIL.COM', 'FIAP01',2);

INSERT INTO CATEGORIA_RESTAURANTE(nome) VALUES ('LANCHE');
INSERT INTO CATEGORIA_RESTAURANTE(nome) VALUES ('ARABE');

INSERT INTO CLIENTE(cpf,nome, sobrenome, telefone, idade, usuario_id) VALUES('123123','Fulano','Ciclano', '1234-1234', 30,1);
INSERT INTO CLIENTE(cpf,nome, sobrenome, telefone, idade, usuario_id) VALUES('123123','Alan','Zica', '1234-1234', 50,4);
INSERT INTO RESTAURANTE(cnpj,nome, email, telefone, imagem, usuario_id, categoria_restaurante_id) VALUES('123123','FulanoRestaurante','RESTAURANTE@TOP.COM','1234-1234',null, 2,1);
INSERT INTO RESTAURANTE(cnpj,nome, email, telefone, imagem, usuario_id, categoria_restaurante_id) VALUES('123123','JubileuRestaurante','RESTAURANTE@TOP.COM','1234-1234',null, 5,2);
INSERT INTO ENTREGADOR(cpf,nome, sobrenome, telefone, idade, usuario_id) VALUES('123123','Beltrano','Ciclano', '1234-1234', 40,3);

INSERT INTO LOCAL(NOME,EMAIL,TELEFONE, ENDERECO) VALUES('Arena-Corinthians','ArenaCorinthians@gmail.com','1234-1234',' Av. Miguel Ignácio Curi, 111');
INSERT INTO LOCAL(NOME,EMAIL,TELEFONE, ENDERECO) VALUES('Arena-Palmeiras','ArenaPalmeiras@gmail.com','1234-1234',' Av. Francisco Matarazzo, 1705');
INSERT INTO SETOR(NOME) VALUES ('NORTE');
INSERT INTO SETOR(NOME) VALUES ('SUL');
INSERT INTO SETOR(NOME) VALUES ('LESTE');
INSERT INTO SETOR(NOME) VALUES ('OESTE');
INSERT INTO BLOCO(NOME, NUMERO) VALUES ('A',10);
INSERT INTO BLOCO(NOME, NUMERO) VALUES ('B',20);
INSERT INTO BLOCO(NOME, NUMERO) VALUES ('C',30);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (1,1);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (1,2);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (1,3);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (1,4);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (2,1);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (2,2);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (2,3);
INSERT INTO LOCAL_SETOR(LOCAL_ID, SETOR_ID) VALUES (2,4);
INSERT INTO LOCAL_SETOR_BLOCO(LOCAL_SETOR_ID, BLOCO_ID) VALUES (1,1);
INSERT INTO LOCAL_SETOR_BLOCO(LOCAL_SETOR_ID, BLOCO_ID) VALUES (1,2);
INSERT INTO LOCAL_SETOR_BLOCO(LOCAL_SETOR_ID, BLOCO_ID) VALUES (1,3);
INSERT INTO LOCAL_SETOR_BLOCO(LOCAL_SETOR_ID, BLOCO_ID) VALUES (2,1);
INSERT INTO LOCAL_SETOR_BLOCO(LOCAL_SETOR_ID, BLOCO_ID) VALUES (2,2);
INSERT INTO LOCAL_SETOR_BLOCO(LOCAL_SETOR_ID, BLOCO_ID) VALUES (2,3);

INSERT INTO PRODUTO(CATEGORIA_PRODUTO) VALUES ('HAMBURGUER');
INSERT INTO PRODUTO(CATEGORIA_PRODUTO) VALUES ('REFRIGERANTE');
INSERT INTO PRODUTO(CATEGORIA_PRODUTO) VALUES ('HOT-DOG');

INSERT INTO RESTAURANTE_PRODUTO(HABILITADO_VENDA, PRECO, IMAGEM, NOME_PERSONALIZADO, DETALHES, RESTAURANTE_ID, PRODUTO_ID) VALUES (true, 29.90, null, 'HAMBURG', 'SUCULENTO E BOM', 1, 1);
INSERT INTO RESTAURANTE_PRODUTO(HABILITADO_VENDA, PRECO, IMAGEM, NOME_PERSONALIZADO, DETALHES, RESTAURANTE_ID, PRODUTO_ID) VALUES (true, 49.90, null, 'COCA-COLA','BEBIDA', 1, 2);

INSERT INTO CLIENTE_LOCAL_SETOR_BLOCO(CLIENTE_ID, LOCAL_SETOR_BLOCO_ID, DATA_PRESENTE) VALUES (1,1,CURRENT_DATE);
INSERT INTO ENTREGADOR_LOCAL_SETOR(ENTREGADOR_ID, LOCAL_SETOR_ID, DATA_PRESENTE) VALUES (1,1, CURRENT_DATE);
INSERT INTO RESTAURANTE_LOCAL_SETOR(RESTAURANTE_ID, LOCAL_SETOR_ID) VALUES (1,1);

INSERT INTO PEDIDO(DATA, HORA,CLIENTE_LOCAL_SETOR_BLOCO_ID,RESTAURANTE_LOCAL_SETOR_ID, ENTREGADOR_LOCAL_SETOR_ID, TIPO_ENTREGA_ID, STATUS_ID) VALUES (CURRENT_DATE, CURRENT_TIME, 1,1,1,2,4);
INSERT INTO PEDIDO(DATA, HORA,CLIENTE_LOCAL_SETOR_BLOCO_ID,RESTAURANTE_LOCAL_SETOR_ID, ENTREGADOR_LOCAL_SETOR_ID, TIPO_ENTREGA_ID, STATUS_ID) VALUES (CURRENT_DATE, CURRENT_TIME, 1,1,NULL,2,1);
INSERT INTO PEDIDO_PRODUTO(QUANTIDADE, OBSERVACAO, RESTAURANTE_PRODUTO_ID, PEDIDO_ID) VALUES (1,NULL,1,1);
INSERT INTO PEDIDO_PRODUTO(QUANTIDADE, OBSERVACAO, RESTAURANTE_PRODUTO_ID, PEDIDO_ID) VALUES (1,NULL,1,1);

